CREATE TABLE WEIGHT (
  ID VARCHAR(32),
  USERNAME VARCHAR(20) DEFAULT NULL,
  WEIGHT DOUBLE DEFAULT 0,
  RECORD_TIME TIMESTAMP  ,
  DESCRIPTION VARCHAR(512) DEFAULT NULL,
  CREATEID VARCHAR(32),
  CREATETIME TIMESTAMP  ,
  UPDATEID VARCHAR(32) , 
  UPDATETIME TIMESTAMP,
  DELETED VARCHAR(1) DEFAULT NULL,
  VERSION INT, 
  PRIMARY KEY (ID)
);