CREATE TABLE USERS (
  ID VARCHAR(32),
  USERNAME VARCHAR(20) DEFAULT NULL,
  PASSWORD VARCHAR(60) DEFAULT NULL,
  CREATEID VARCHAR(32),
  CREATETIME TIMESTAMP  ,
  UPDATEID VARCHAR(32) , 
  UPDATETIME TIMESTAMP,
  DELETED VARCHAR(1) DEFAULT NULL,
  VERSION INT, 
  PRIMARY KEY (ID)
);
------------------------------------------------
CREATE TABLE ROLES (
  ID VARCHAR(32),
  ROLECODE VARCHAR(20) DEFAULT NULL,
  ROLENAME VARCHAR(60) DEFAULT NULL,
  CREATEID VARCHAR(32),
  CREATETIME TIMESTAMP  ,
  UPDATEID VARCHAR(32) , 
  UPDATETIME TIMESTAMP,
  DELETED VARCHAR(1) DEFAULT NULL,
  VERSION INT, 
  PRIMARY KEY (ID)
) ;
----------------------------------------------
CREATE TABLE RESOURCES (
  ID VARCHAR(32),
  URL VARCHAR(128) DEFAULT NULL,
  DESCRIPTION VARCHAR(60) DEFAULT NULL,
  CREATEID VARCHAR(32),
  CREATETIME TIMESTAMP  ,
  UPDATEID VARCHAR(32) , 
  UPDATETIME TIMESTAMP,
  DELETED VARCHAR(1) DEFAULT NULL,
  VERSION INT, 
  PRIMARY KEY (ID)
) ;
------------------------------------------------------
CREATE TABLE RESOURCES_ALLOCATED (
  ID VARCHAR(32),
  RESOURCEID VARCHAR(128) DEFAULT NULL,
  ALLOCATEDID VARCHAR(60) DEFAULT NULL, -- ROLE , OR GROUP 
  CREATEID VARCHAR(32),
  CREATETIME TIMESTAMP  ,
  UPDATEID VARCHAR(32) , 
  UPDATETIME TIMESTAMP,
  DELETED VARCHAR(1) DEFAULT NULL,
  VERSION INT, 
  PRIMARY KEY (ID)
) ;
------------------------------------------------------
CREATE TABLE USER_TRACKER (
  ID VARCHAR(32),
  USERID VARCHAR(32),
  USERNAME VARCHAR(20) DEFAULT NULL,
  IP VARCHAR(32) DEFAULT NULL,
  LOGIN_TIME TIMESTAMP  ,
  LOGIN_CLIENT VARCHAR(256),
  CREATEID VARCHAR(32),
  CREATETIME TIMESTAMP  ,
  UPDATEID VARCHAR(32) , 
  UPDATETIME TIMESTAMP,
  DELETED VARCHAR(1) DEFAULT NULL,
  VERSION INT, 
  PRIMARY KEY (ID)
) ;
