CREATE TABLE PARAM_CODE (
  ID VARCHAR(32),
  TYPE VARCHAR(32) DEFAULT NULL,
  CODE VARCHAR(32) DEFAULT NULL,
  NAME VARCHAR(128) DEFAULT NULL,
  DESCRIPTION VARCHAR(512) DEFAULT NULL,
  CREATEID VARCHAR(32),
  CREATETIME TIMESTAMP  ,
  UPDATEID VARCHAR(32) , 
  UPDATETIME TIMESTAMP,
  DELETED VARCHAR(1) DEFAULT NULL,
  VERSION INT, 
  PRIMARY KEY (ID)
);

CREATE TABLE PARAM_TYPE (
  ID VARCHAR(32),
  CODE VARCHAR(32) DEFAULT NULL,
  NAME VARCHAR(128) DEFAULT NULL,
  DESCRIPTION VARCHAR(512) DEFAULT NULL,
  CREATEID VARCHAR(32),
  CREATETIME TIMESTAMP  ,
  UPDATEID VARCHAR(32) , 
  UPDATETIME TIMESTAMP,
  DELETED VARCHAR(1) DEFAULT NULL,
  VERSION INT, 
  PRIMARY KEY (ID)
);