CREATE TABLE RuntimeLoad (
  ID VARCHAR(32),
  NAME VARCHAR(32),
  DESCRIPTION VARCHAR(512) DEFAULT NULL,
  CREATEID VARCHAR(32),
  CREATETIME TIMESTAMP  ,
  UPDATEID VARCHAR(32) , 
  UPDATETIME TIMESTAMP,
  DELETED VARCHAR(1) DEFAULT NULL,
  VERSION INT, 
  PRIMARY KEY (ID)
);