insert into ROLES(ROLE_CODE,ROLE_NAME,DESCRIPTION,CREATEID,ID,UPDATEID,CREATETIME,UPDATETIME,DELETED,VERSION)values('DEFAULT','默认角色','所有没有其他角色的用户自动并入此角色','YouAPP',UUID(),'YouAPP',SYSDATE(),SYSDATE(),'N',1);
insert into ROLES(ROLE_CODE,ROLE_NAME,DESCRIPTION,CREATEID,ID,UPDATEID,CREATETIME,UPDATETIME,DELETED,VERSION)values('ADMIN','管理员角色','此角色用户拥有最高权限','YouAPP',UUID(),'YouAPP',SYSDATE(),SYSDATE(),'N',1);

insert into GROUPS(GROUP_CODE,GROUP_NAME,DESCRIPTION,CREATEID,ID,UPDATEID,CREATETIME,UPDATETIME,DELETED,VERSION)values('DEFAULT','默认组','不在其他组的用户自动并入此组','YouAPP',UUID(),'YouAPP',SYSDATE(),SYSDATE(),'N',1);
insert into GROUPS(GROUP_CODE,GROUP_NAME,DESCRIPTION,CREATEID,ID,UPDATEID,CREATETIME,UPDATETIME,DELETED,VERSION)values('ADMIN','管理员组','此组用户拥有最高权限','YouAPP',UUID(),'YouAPP',SYSDATE(),SYSDATE(),'N',1);
