CREATE TABLE RESOURCES_ACTION (
  ID VARCHAR(32),
  RESOURCEID VARCHAR(32) DEFAULT NULL,
  URL VARCHAR(128) DEFAULT NULL,
  ACTION VARCHAR(20) DEFAULT NULL,
  DESCRIPTION VARCHAR(60) DEFAULT NULL,
  CREATEID VARCHAR(32),
  CREATETIME TIMESTAMP  ,
  UPDATEID VARCHAR(32) , 
  UPDATETIME TIMESTAMP,
  DELETED VARCHAR(1) DEFAULT NULL,
  VERSION INT, 
  PRIMARY KEY (ID)
);

