-------------------RESOURCES---------------------------
CREATE TABLE RESOURCES (
  ID VARCHAR(32),
  URL VARCHAR(128) DEFAULT NULL,
  DESCRIPTION VARCHAR(256) DEFAULT NULL,
  CREATEID VARCHAR(32),
  CREATETIME TIMESTAMP  ,
  UPDATEID VARCHAR(32) , 
  UPDATETIME TIMESTAMP,
  DELETED VARCHAR(1) DEFAULT NULL,
  VERSION INT, 
  PRIMARY KEY (ID)
) ;
-------------------------------------------------------
CREATE TABLE RESOURCES_EXTEND (
  ID VARCHAR(32),
  RESOURCEID VARCHAR(32) DEFAULT NULL,
  URL VARCHAR(128) DEFAULT NULL,
  ACTION VARCHAR(64) DEFAULT NULL,
  DESCRIPTION VARCHAR(256) DEFAULT NULL,
  CREATEID VARCHAR(32),
  CREATETIME TIMESTAMP  ,
  UPDATEID VARCHAR(32) , 
  UPDATETIME TIMESTAMP,
  DELETED VARCHAR(1) DEFAULT NULL,
  VERSION INT, 
  PRIMARY KEY (ID)
);
-----------------------RESOURCES_ROLES-------------------------------
CREATE TABLE RESOURCES_ROLES (
  ID VARCHAR(32),
  RESOURCEID VARCHAR(32) DEFAULT NULL,
  ROLEID VARCHAR(32) DEFAULT NULL,
  DESCRIPTION VARCHAR(256) DEFAULT NULL,
  ENABLE VARCHAR(1) DEFAULT NULL,
  CREATEID VARCHAR(32),
  CREATETIME TIMESTAMP  ,
  UPDATEID VARCHAR(32) , 
  UPDATETIME TIMESTAMP,
  DELETED VARCHAR(1) DEFAULT NULL,
  VERSION INT, 
  PRIMARY KEY (ID)
) ;
-----------------------RESOURCES_GROUPS-------------------------------
CREATE TABLE RESOURCES_GROUPS (
  ID VARCHAR(32),
  RESOURCEID VARCHAR(32) DEFAULT NULL,
  GROUPID VARCHAR(32) DEFAULT NULL, 
  ENABLE VARCHAR(1) DEFAULT NULL,
  DESCRIPTION VARCHAR(256) DEFAULT NULL,
  CREATEID VARCHAR(32),
  CREATETIME TIMESTAMP  ,
  UPDATEID VARCHAR(32) , 
  UPDATETIME TIMESTAMP,
  DELETED VARCHAR(1) DEFAULT NULL,
  VERSION INT, 
  PRIMARY KEY (ID)
) ;


