CREATE TABLE BILL (
  ID VARCHAR(32),
  USER_CODE VARCHAR(32) DEFAULT NULL,
  MONEY DOUBLE DEFAULT 0,
  GOOD_NAME VARCHAR(64) DEFAULT NULL,
  GOOD_TYPE VARCHAR(32) DEFAULT NULL,
  MALL_CODE VARCHAR(32) DEFAULT NULL,
  MALL_NAME VARCHAR(256) DEFAULT NULL,
  BILL_TIME TIMESTAMP  ,
  DESCRIPTION VARCHAR(512) DEFAULT NULL,
  CREATEID VARCHAR(32),
  CREATETIME TIMESTAMP  ,
  UPDATEID VARCHAR(32) , 
  UPDATETIME TIMESTAMP,
  DELETED VARCHAR(1) DEFAULT NULL,
  VERSION INT, 
  PRIMARY KEY (ID)
);